[INFO   ] Logger: Record log in /storage/emulated/0/organizer/.kivy/logs/kivy_20-06-10_3.txt
[INFO   ] Kivy: v1.11.0.dev0, git-8b6af30, 20190320
[INFO   ] Python: v3.7.2 (default, Mar 20 2019, 15:02:54) 
[GCC 8.2.0]
[INFO   ] KivyMD: v0.104.1
[INFO   ] Factory: 184 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 3.2 V@331.0 (GIT@50f1b2d, I1b05bd271c) (Date:04/09/19)'>
[INFO   ] GL: OpenGL vendor <b'Qualcomm'>
[INFO   ] GL: OpenGL renderer <b'Adreno (TM) 505'>
[INFO   ] GL: OpenGL parsed version: 3, 2
[INFO   ] GL: Texture max size <16384>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] GL: NPOT texture support is available
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/storage/emulated/0/organizer/nav.py", line 256, in <module>
[WARNING] stderr:     list_covid = pd.read_csv('https://opendata.ecdc.europa.eu/covid19/casedistribution/csv')
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
[WARNING] stderr:     return _read(filepath_or_buffer, kwds)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pandas/io/parsers.py", line 431, in _read
[WARNING] stderr:     filepath_or_buffer, encoding, compression
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/pandas/io/common.py", line 177, in get_filepath_or_buffer
[WARNING] stderr:     reader = BytesIO(req.read())
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/http/client.py", line 460, in read
[WARNING] stderr:     s = self._safe_read(self.length)
[WARNING] stderr:   File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/http/client.py", line 612, in _safe_read
[WARNING] stderr:     raise IncompleteRead(b''.join(s), amt)
[WARNING] stderr: http.client.IncompleteRead: IncompleteRead(1100194 bytes read, 207033 more expected)
